#!/bin/bash
case "`grep DISTRIB_CODENAME /etc/*-release | awk -F '=' '{print $2}'`" in
     xenial)
              if [ "$(whoami)" != "root" ]
                 then
                  echo "You need to login as root to use this script! Sorry!";
                 exit 1
              fi 
              apt-get update && apt-get upgrade -y 
              apt-get dist-upgrade -y; apt-get autoremove -y
     ;;
esac
